# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 19:54
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('eating_time', bitfield.models.BitField((('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('after_lunch', 'After lunch'), ('dinner', 'Dinner')), default=None)),
                ('serve_type', bitfield.models.BitField((('garnier', 'Garnier'), ('desert', 'Desert'), ('bad', 'BAD')), default=None)),
                ('proteinsNumber', models.IntegerField(default=0)),
                ('lipidsNumber', models.IntegerField(default=0)),
                ('energyValue', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Food category',
                'verbose_name_plural': 'Food categories',
            },
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('proteinsNumber', models.IntegerField(default=0)),
                ('lipidsNumber', models.IntegerField(default=0)),
                ('energyValue', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
            ],
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='food_type',
            field=models.ManyToManyField(to='health_calc.FoodType'),
        ),
        migrations.AddField(
            model_name='dish',
            name='food_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_calc.FoodCategory'),
        ),
        migrations.AddField(
            model_name='dish',
            name='food_type',
            field=models.ManyToManyField(to='health_calc.FoodType'),
        ),
        migrations.AddField(
            model_name='dish',
            name='products',
            field=models.ManyToManyField(to='health_calc.Product'),
        ),
    ]
