# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_calc', '0002_auto_20170516_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishescompabilities',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dishespheromones',
            name='name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
